// app/components/NavBar.tsx
'use client';

import { useEffect, useState } from 'react';
import Link from 'next/link';
import { useRouter, usePathname } from 'next/navigation';
import { supabase } from '@/lib/supabase';
import type { User } from '@supabase/supabase-js';

export default function NavBar() {
  const router = useRouter();
    const pathname = usePathname();
      const [user, setUser] = useState<User | null>(null);
        const [loading, setLoading] = useState(true);

          useEffect(() => {
              // Get current session on load
                  supabase.auth.getUser().then(({ data }) => {
                        setUser(data.user ?? null);
                              setLoading(false);
                                  });

                                      // Listen for login/logout events — updates navbar instantly
                                          const { data: listener } = supabase.auth.onAuthStateChange((_event, session) => {
                                                setUser(session?.user ?? null);
                                                    });

                                                        return () => listener.subscription.unsubscribe();
                                                          }, []);

                                                            async function handleSignOut() {
                                                                await supabase.auth.signOut();
                                                                    // Clear localStorage monitors on sign out so other users don't see them
                                                                        localStorage.removeItem('clauseguard_monitors_v2');
                                                                            router.push('/');
                                                                                router.refresh();
                                                                                  }

                                                                                    // Don't flash the wrong state while checking
                                                                                      if (loading) return (
                                                                                          <nav>
                                                                                                <Link href="/" className="logo">
                                                                                                        <div className="logo-shield" />
                                                                                                                ClauseGuard
                                                                                                                      </Link>
                                                                                                                            <div className="nav-links">
                                                                                                                                    <Link href="/propwatch" className="nav-link">PropWatch</Link>
                                                                                                                                            <Link href="/monitor" className="nav-link">⚙ Account Monitor</Link>
                                                                                                                                                  </div>
                                                                                                                                                        <div className="nav-right">
                                                                                                                                                                <div style={{ width: 120 }} /> {/* placeholder to prevent layout shift */}
                                                                                                                                                                      </div>
                                                                                                                                                                          </nav>
                                                                                                                                                                            );

                                                                                                                                                                              return (
                                                                                                                                                                                  <nav>
                                                                                                                                                                                        <Link href="/" className="logo">
                                                                                                                                                                                                <div className="logo-shield" />
                                                                                                                                                                                                        ClauseGuard
                                                                                                                                                                                                              </Link>

                                                                                                                                                                                                                    <div className="nav-links">
                                                                                                                                                                                                                            <Link href="/propwatch" className="nav-link" style={{ color: pathname === '/propwatch' ? 'var(--ink)' : '' }}>
                                                                                                                                                                                                                                      PropWatch
                                                                                                                                                                                                                                              </Link>
                                                                                                                                                                                                                                                      <Link href="/monitor" className="nav-link" style={{ color: pathname === '/monitor' ? 'var(--ink)' : '' }}>
                                                                                                                                                                                                                                                                ⚙ Account Monitor
                                                                                                                                                                                                                                                                        </Link>
                                                                                                                                                                                                                                                                                <Link href="/pricing" className="nav-link" style={{ color: pathname === '/pricing' ? 'var(--ink)' : '' }}>
                                                                                                                                                                                                                                                                                          Pricing
                                                                                                                                                                                                                                                                                                  </Link>
                                                                                                                                                                                                                                                                                                        </div>

                                                                                                                                                                                                                                                                                                              <div className="nav-right">
                                                                                                                                                                                                                                                                                                                      {user ? (
                                                                                                                                                                                                                                                                                                                                // ── LOGGED IN: show email + dashboard + sign out ──
                                                                                                                                                                                                                                                                                                                                          <>
                                                                                                                                                                                                                                                                                                                                                      <span style={{ fontSize: 12, color: 'var(--ink-muted)', maxWidth: 160, overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}>
                                                                                                                                                                                                                                                                                                                                                                    {user.email}
                                                                                                                                                                                                                                                                                                                                                                                </span>
                                                                                                                                                                                                                                                                                                                                                                                            <Link href="/dashboard" className="btn btn-ghost">
                                                                                                                                                                                                                                                                                                                                                                                                          Dashboard
                                                                                                                                                                                                                                                                                                                                                                                                                      </Link>
                                                                                                                                                                                                                                                                                                                                                                                                                                  <button className="btn btn-ghost" onClick={handleSignOut}
                                                                                                                                                                                                                                                                                                                                                                                                                                                style={{ color: 'var(--ink-muted)', borderColor: 'var(--border)' }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                              Sign Out
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ) : (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      // ── LOGGED OUT: show dashboard link + sign in ──
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <Link href="/dashboard" className="btn btn-ghost">My Dashboard</Link>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <Link href="/login" className="btn btn-primary">Sign In</Link>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </nav>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      