// app/monitor/page.tsx
'use client';

import { useState, useEffect, useCallback, Suspense } from 'react';
import { useSearchParams } from 'next/navigation';
import { supabase } from '@/lib/supabase';
import PremiumModal from '../components/PremiumModal';
import type { User } from '@supabase/supabase-js';

interface Monitor {
  id: string; firmName: string; accountType: string; accountSize: string;
    tcUrl: string; description: string; addedAt: string; status: 'monitoring' | 'changed' | 'pending';
      changeLog: { detectedAt: string; summary: string; impact: string }[];
        lastChecked: string | null; snapshotHash: string | null;
        }

        function simpleHash(str: string): string {
          let hash = 0;
            for (let i = 0; i < str.length; i++) { hash = ((hash << 5) - hash) + str.charCodeAt(i); hash = hash & hash; }
              return hash.toString(36);
              }

              function MonitorPageInner() {
                const searchParams = useSearchParams();
                  const [authChecked, setAuthChecked] = useState(false);
                    const [isLoggedIn, setIsLoggedIn] = useState(false);
                      const [user, setUser] = useState<User | null>(null);
                        const [showModal, setShowModal] = useState(false);
                          const [monitors, setMonitors] = useState<Monitor[]>([]);
                            const [prompt, setPrompt] = useState('');
                              const [urlInput, setUrlInput] = useState('');
                                const [adding, setAdding] = useState(false);
                                  const [toast, setToast] = useState('');

                                    const fetchMonitors = useCallback(async (userId: string) => {
                                        const { data } = await supabase.from('account_monitors').select('*').eq('user_id', userId).order('created_at', { ascending: false });
                                            if (data) {
                                                  setMonitors(data.map(d => ({
                                                          id: d.id, firmName: d.firm_name, accountType: d.account_type, accountSize: d.account_size,
                                                                  tcUrl: d.tc_url, description: d.description || '', addedAt: d.created_at, status: d.status as any,
                                                                          changeLog: d.change_log || [], lastChecked: d.last_checked, snapshotHash: d.content_hash
                                                                                })));
                                                                                    }
                                                                                      }, []);

                                                                                        useEffect(() => {
                                                                                            supabase.auth.getSession().then(({ data: { session } }) => {
                                                                                                  setIsLoggedIn(!!session?.user); setUser(session?.user ?? null); setAuthChecked(true);
                                                                                                        if (!session?.user) setShowModal(true);
                                                                                                              if (session?.user) fetchMonitors(session.user.id);
                                                                                                                  });
                                                                                                                      const prePrompt = searchParams.get('prompt');
                                                                                                                          if (prePrompt) setPrompt(prePrompt);
                                                                                                                            }, [searchParams, fetchMonitors]);

                                                                                                                              function showToast(msg: string) { setToast(msg); setTimeout(() => setToast(''), 3500); }

                                                                                                                                async function handleAdd() {
                                                                                                                                    if (!isLoggedIn) { setShowModal(true); return; }
                                                                                                                                        if (!prompt.trim()) { showToast('⚠️ Describe your account first'); return; }
                                                                                                                                            if (!user) return;
                                                                                                                                                setAdding(true);
                                                                                                                                                    try {
                                                                                                                                                          const res = await fetch('/api/monitor-parse', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ promptText: prompt }) });
                                                                                                                                                                if (!res.ok) throw new Error('Parse failed');
                                                                                                                                                                      const data = await res.json();
                                                                                                                                                                            if (data.error) throw new Error(data.error);

                                                                                                                                                                                  // THIS IS THE SUPABASE FIX - Saving to the Magic Toybox
                                                                                                                                                                                        await supabase.from('account_monitors').insert({
                                                                                                                                                                                                user_id: user.id, firm_name: data.firmName || '', account_type: data.accountType || 'Unknown',
                                                                                                                                                                                                        account_size: data.accountSize || 'Not specified', tc_url: urlInput || data.suggestedUrl || '',
                                                                                                                                                                                                                description: data.monitorDescription || '', status: 'monitoring', change_log: []
                                                                                                                                                                                                                      });

                                                                                                                                                                                                                            fetchMonitors(user.id); setPrompt(''); setUrlInput('');
                                                                                                                                                                                                                                  showToast('🛡 Monitor added! ' + (data.firmName || ''));
                                                                                                                                                                                                                                      } catch (err: unknown) { showToast('❌ ' + (err instanceof Error ? err.message : 'Failed')); }
                                                                                                                                                                                                                                          setAdding(false);
                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                              async function deleteMonitor(id: string) {
                                                                                                                                                                                                                                                  await supabase.from('account_monitors').delete().eq('id', id);
                                                                                                                                                                                                                                                      if (user) fetchMonitors(user.id); showToast('Monitor removed');
                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                          if (!authChecked) return <div style={{ minHeight: '100vh', display: 'flex', alignItems: 'center', justifyContent: 'center' }}><div style={{ fontSize: 40, animation: 'shieldPulse 1.5s infinite' }}>🛡️</div></div>;

                                                                                                                                                                                                                                                            return (
                                                                                                                                                                                                                                                                <>
                                                                                                                                                                                                                                                                      {showModal && <PremiumModal onClose={() => setShowModal(false)} />}
                                                                                                                                                                                                                                                                            <div className="monitor-layout" style={{ filter: !isLoggedIn ? 'blur(3px)' : 'none', pointerEvents: !isLoggedIn ? 'none' : 'auto' }}>
                                                                                                                                                                                                                                                                                    <div className="monitor-page-header"><h1>My Monitored Accounts</h1></div>
                                                                                                                                                                                                                                                                                            <div className="monitor-add-card">
                                                                                                                                                                                                                                                                                                      <div className="monitor-add-header"><div className="monitor-add-icon">+</div><div className="monitor-add-title">Add Account to Monitor</div></div>
                                                                                                                                                                                                                                                                                                                <div className="monitor-add-body">
                                                                                                                                                                                                                                                                                                                            <textarea className="monitor-prompt-input" value={prompt} onChange={e => setPrompt(e.target.value)} placeholder='"Monitor FTMO 10k"' rows={3} />
                                                                                                                                                                                                                                                                                                                                        <input type="text" className="url-input" style={{ width: '100%', marginTop: 6 }} value={urlInput} onChange={e => setUrlInput(e.target.value)} placeholder="T&C URL (optional)" />
                                                                                                                                                                                                                                                                                                                                                    <button className="scan-btn" style={{ width: '100%', justifyContent: 'center', marginTop: 12 }} onClick={handleAdd} disabled={adding}>{adding ? '🤖 Setting up...' : '🛡 Add Monitor →'}</button>
                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                              {monitors.length === 0 ? <div className="monitor-empty"><div className="empty-title">No accounts monitored yet</div></div> : (
                                                                                                                                                                                                                                                                                                                                                                                        <div className="monitor-list">
                                                                                                                                                                                                                                                                                                                                                                                                    {monitors.map(m => (
                                                                                                                                                                                                                                                                                                                                                                                                                    <div key={m.id} className="monitor-card">
                                                                                                                                                                                                                                                                                                                                                                                                                                      <div className="monitor-card-top"><div><div className="monitor-card-firm">{m.firmName}</div><div className="monitor-card-account">{m.accountType}</div></div></div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                        {m.tcUrl ? <div className="monitor-card-url">🔗 {m.tcUrl}</div> : <div className="monitor-card-url">No URL</div>}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div className="monitor-card-footer"><button className="monitor-delete-btn" onClick={() => deleteMonitor(m.id)}>✕ Remove</button></div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div className={`toast${toast ? ' show' : ''}`}>{toast}</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          export default function MonitorPage() {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            return <Suspense fallback={<div style={{ padding: '100px 40px' }}>Loading...</div>}><MonitorPageInner /></Suspense>;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
